[build]
  # Build both frontend and backend
  command = "npm install && npm run build && pip install -r requirements.txt"
  functions = "netlify/functions"
  publish = "dist"

[build.environment]
  PYTHON_VERSION = "3.11"
  NODE_VERSION = "18"

# Redirect all API calls to Netlify Functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Redirect root to a simple HTML page
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Netlify Functions configuration
[functions]
  node_bundler = "esbuild"
