# Render deployment configuration for Notebooker
services:
  # Web Application
  - type: web
    name: notebooker
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.4"
      - key: FLASK_ENV
        value: "production"
      - key: SECRET_KEY
        generateValue: true
    healthCheckPath: /
    autoDeploy: true